#!/usr/bin/env node
/**
 * Exports the data the native apps share with the web app into ../shared:
 *
 *   shared/parks.json             the 31 parks, sv/en text, official URLs
 *   shared/map.json               hex-map geometry
 *   shared/passcode-vectors.json  transfer codes produced by THIS codec
 *
 * The web app stays the source of truth: parks.ts, mapHexes.ts and
 * passcode.ts are imported directly, so the JSON can't drift from what the
 * site serves. The Android build reads these files as assets, and its unit
 * tests replay the vectors — a phone and a browser that disagree on a single
 * bit would stop codes moving between them.
 *
 * Run after changing any of those three files, and commit the result:
 *   npm run export:shared
 */
import { registerHooks } from "node:module";
import { writeFile } from "node:fs/promises";
import { fileURLToPath } from "node:url";

const SRC = new URL("../src/", import.meta.url);

// passcode.ts imports todayISO from visited.tsx, which is React + JSX and
// can't be type-stripped. The vectors never hit the "unknown date" branch
// that calls it, so a stub is enough.
const VISITED_STUB =
  "data:text/javascript," +
  encodeURIComponent(
    "export const todayISO = () => new Date().toLocaleDateString('sv-SE');",
  );

registerHooks({
  resolve(specifier, context, next) {
    if (specifier === "@/lib/visited") return { url: VISITED_STUB, shortCircuit: true };
    if (specifier.startsWith("@/")) {
      return next(new URL(`${specifier.slice(2)}.ts`, SRC).href, context);
    }
    return next(specifier, context);
  },
});

const { PARKS, PIN_ARTWORK, officialUrl } = await import("../src/data/parks.ts");
const { MAP_VIEWBOX, LAND_HEXES, PARK_HEXES } = await import("../src/data/mapHexes.ts");
const { CODE_ORDER, encodeVisits, decodeVisits } = await import("../src/lib/passcode.ts");

const OUT = new URL("../../shared/", import.meta.url);

async function write(name, value) {
  await writeFile(fileURLToPath(new URL(name, OUT)), JSON.stringify(value, null, 2) + "\n");
  console.log(`wrote shared/${name}`);
}

const HEADER =
  "Generated by parkpass-web/scripts/export-shared.mjs — do not edit by hand.";

await write("parks.json", {
  _comment: HEADER,
  parks: PARKS.map((p) => ({
    slug: p.slug,
    name: p.name,
    ...(p.sami ? { sami: p.sami } : {}),
    year: p.year,
    area: p.area,
    glyph: p.glyph,
    color: p.color,
    region: p.region,
    description: p.description,
    officialUrl: { sv: officialUrl(p.slug, "sv"), en: officialUrl(p.slug, "en") },
    hasArtwork: PIN_ARTWORK.has(p.slug),
  })),
});

const [, , vbWidth, vbHeight] = MAP_VIEWBOX.split(" ").map(Number);
await write("map.json", {
  _comment: HEADER,
  viewBox: { width: vbWidth, height: vbHeight },
  land: LAND_HEXES,
  parks: PARK_HEXES,
});

// --- Transfer-code vectors -------------------------------------------------

const everyPark = Object.fromEntries(
  CODE_ORDER.map((slug, i) => [slug, isoPlusDays("2020-01-02", i * 97)]),
);

const boards = {
  single: { abisko: "2026-07-24" },
  lastSlot: { tresticklan: "2021-05-01" },
  scattered: {
    sarek: "2023-08-14",
    tyresta: "2020-01-02",
    "gotska-sandon": "2024-06-30",
    stenshuvud: "2025-12-31",
    kosterhavet: "2026-02-28",
  },
  // Dates outside the 14-bit window clamp to day 1 and day 16383.
  clamped: { abisko: "2019-06-01", muddus: "2099-01-01" },
  everyPark,
};

const encode = Object.entries(boards).map(([name, visits]) => ({
  name,
  visits,
  code: encodeVisits(visits),
}));

// Round-trip expectations — decode(code) as the web app sees it.
for (const v of encode) {
  const r = decodeVisits(v.code);
  if (!r.ok) throw new Error(`vector ${v.name} failed to decode: ${r.error}`);
  v.decoded = r.visits;
}

const sample = encode.find((v) => v.name === "scattered").code;
const decodeCases = [
  ["lowercase", sample.toLowerCase()],
  ["noPrefix", sample.replace(/^PARKPASS-/, "")],
  ["spaced", `  ${sample.replaceAll("-", " ")} \n`],
  ["crockfordAliases", sample.replaceAll("0", "O").replaceAll("1", "l")],
  ["empty", "   "],
  ["prefixOnly", "PARKPASS-"],
  ["notACode", "hello!"],
  ["badChar", "PARKPASS-ABCU"],
  ["tooShort", "PARKPASS-AB"],
  ["typo", flipChar(sample)],
  ["futureVersion", forgeVersion(2)],
].map(([name, input]) => ({ name, input, result: decodeVisits(input) }));

await write("passcode-vectors.json", {
  _comment: HEADER,
  codeOrder: CODE_ORDER,
  encode,
  decode: decodeCases,
});

function isoPlusDays(iso, days) {
  const d = new Date(`${iso}T00:00:00Z`);
  d.setUTCDate(d.getUTCDate() + days);
  return d.toISOString().slice(0, 10);
}

/** Changes one body character so the checksum no longer matches. */
function flipChar(code) {
  const i = "PARKPASS-".length + 2;
  const ch = code[i] === "A" ? "B" : "A";
  return code.slice(0, i) + ch + code.slice(i + 1);
}

/** A well-formed, correctly checksummed code with an unknown version. */
function forgeVersion(version) {
  const ALPHABET = "0123456789ABCDEFGHJKMNPQRSTVWXYZ";
  // 4 version bits + 31 empty bitmap bits = 35 bits = 7 characters.
  const bits = version.toString(2).padStart(4, "0") + "0".repeat(31);
  const values = bits.match(/.{5}/g).map((b) => parseInt(b, 2));
  let crc = 0xffff;
  for (const value of values) {
    crc ^= (value << 8) & 0xffff;
    for (let i = 0; i < 8; i++) {
      crc = crc & 0x8000 ? ((crc << 1) ^ 0x1021) & 0xffff : (crc << 1) & 0xffff;
    }
  }
  const checksum = crc & 0x3ff;
  values.push((checksum >> 5) & 31, checksum & 31);
  return "PARKPASS-" + values.map((v) => ALPHABET[v]).join("");
}
